server.port=8081
spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=fitflow
spring.datasource.password=fitflow
spring.jpa.hibernate.ddl-auto=update