spring.application.name=fitflow
spring.datasource.url=jdbc:postgresql://localhost:5432/fitflow
spring.datasource.username=fitflow
spring.datasource.password=fitflow
spring.jpa.hibernate.ddl-auto=update